# Generated by Django 5.2.17 on 2026-08-11 08:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('opening', 'Opening Stock')], db_index=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Always positive; direction comes from transaction_type.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('previous_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_stock', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text='e.g. purchase, sale, adjustment, opening', max_length=64)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_6d60d9_idx'), models.Index(fields=['transaction_type', '-created_at'], name='inventory_s_transac_85a8a5_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_e50b9e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_txn_quantity_gt_0')],
            },
        ),
    ]
