[mysqld]
basedir=C:/laragon/bin/mysql/mysql-8.4.3-winx64
datadir=C:/laragon/data/mysql-8.4.3
port=3306
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
max_allowed_packet=64M

[client]
port=3306
default-character-set=utf8mb4
