# Generated by Django 5.2.17 on 2026-08-11 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('status_change', 'Status Change'), ('export', 'Export'), ('other', 'Other')], db_index=True, max_length=32)),
                ('module', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action', '-created_at'], name='audit_audit_module_02a87e_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]
