# Generated by Django 5.2.17 on 2026-08-11 08:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = customer owes us; negative = we owe customer (advance).', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'name'], name='customers_c_status_57fd05_idx'), models.Index(fields=['city', 'state'], name='customers_c_city_1b2a71_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_gte_0')],
            },
        ),
    ]
