# Generated by Django 5.2.17 on 2026-08-11 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_current_stock_gte_0',
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Maintained via inventory services. May go negative only when ALLOW_NEGATIVE_STOCK is enabled.', max_digits=12),
        ),
    ]
